name: Testing

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main ]


jobs:

  test:
    strategy:
      max-parallel: 6
      matrix:
        go-version: [1.22, 1.23]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Go on the Container
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test the Go code
        run: go test -v ./...