name: Testing

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main ]


jobs:

  test:
    strategy:
      max-parallel: 6
      matrix:
        go-version: [1.21, 1.22]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Go on the Container
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test the Go code
        run: go test -v ./...